name: intentionalistdev/composer-yaml
description: Tool to convert from composer.yml to composer.json.
license: MIT
require:
    symfony/console: '~8'
    symfony/yaml: '~8'
    composer/composer: '~2'
bin:
    - bin/composer-yaml
